### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [Misfit382/JS-minesweeper#1]
1. Katalogi `.idea` i `venv` do wywalenia (*vide* 1. rozdział Poradnika).
2. Z drugiej strony pliki z obrazkami nie zaśmiecałyby widoku, gdyby je schować do podkatalogu.
3. Kostrukcja Pańskiego programu jest przedziwna. Zamiast `from main import *` proszę cały kod zmieścić w jednym pliku. Zdecydowanie wolałbym, żeby klasa `Cell` nie była zagnieżdżona wewnątrz funkcji `mainSweeper`. To samo dotyczy większości funkcji. Tak, jak jest teraz, np. nie da się ich testować. Stałe w rodzaju `CELL_NORMAL` itp., `adjFields` wyciągnąć na początek modułu.
4. Pokaźna większość Pańskich identyfikatorów nosi nazwy zapisane w nieprawidłowym stylu (2. rozdział).
5. Skróty `Col`, `Unc`, `Cont` są niedopuszczalne (2. rozdział).
6. [W tym wierszu](https://github.com/Misfit382/JS-minesweeper/blob/341b09cab536f601daa04f32bab195748768eef9/main.py#L23) zmienił Pan znaczenie wbudowanego identyfikatora `int`. Proszę się zaprzyjaźnić z Pylintem (2. rozdział).
7. Z racji osobliwej architektury kodu nie jestem pewien, czy położenie min jest losowane po pierwszym ruchu (prawidłowo), czy przed nim (nieprawidłowo), ale wydaje mi się, że jest źle.

Po uwzględnieniu powyższych uwag proszę dać mi znać. To jeszcze nie koniec.

**Comment by Misfit382** [comment]
Szanowny Panie Doktorze,
Dzisiaj pojawił się update na temat projektu na Githubie,
Zaleciłem się do większości Pańskich uwag, aczkolwiek co do wiersza który Pan wskazał, wydaje mi się że definiuje tam domyślną wartość zmiennej i tak może zostać. Odnośnie  CELL_NORMAL i tych zmiennych które ładują pliki, zdecydowałem że zostaną one w funkcji gdyż sprawiają problemy po przeniesieniu wyżej.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.
1. Wiersz z punktu 6. teraz jest OK, ale wtedy było w nim [`Mine_Count_Neighbourhood = int = 0`](https://github.com/Misfit382/JS-minesweeper/blob/341b09cab536f601daa04f32bab195748768eef9/main.py#L23).
2. Proszę przeczytać Poradnik i pozmieniać według niego to, co Pan zauważy. Między innymi: puścić pylinta, po czym poprawić nazwy wg jego wskazań; na stałe `CELL_NORMAL` itd. zastosować receptę z 3. rozdziału (w pliku `main.py`); w `gui.py` zastosować się do punktów o importach i funkcji `main()`.

**Comment by Misfit382** [comment]
Szanowny Panie Doktorze, 
przesyłam update. Zgodnie z wcześniejszą prośbą mam wszystko w jednym pliku.

**Comment by MarcinCiura** [comment]
1. Wyrzucić `.vs` (1. rozdział).
2. Posortować importy (2. rozdział).
3. [To](https://github.com/Misfit382/JS-minesweeper/blob/4a055f0ba0b409db8752a20346c43030904deaf8/main.py#L47) i następne małymi literami (2. rozdział). Za to `ADJACENT_FIELDS` dużymi, bez skrótów i na górę, bo to stała (2. rozdział).
4. [Kolory](https://github.com/Misfit382/JS-minesweeper/blob/4a055f0ba0b409db8752a20346c43030904deaf8/main.py#L131) nazwać (2. rozdział); przeczytać narzekania o kolorach w 3. rozdziale.
5. [`flag`](https://github.com/Misfit382/JS-minesweeper/blob/4a055f0ba0b409db8752a20346c43030904deaf8/main.py#L160) nazwać tak, żeby było wiadomo, do czego służy.
6. `init()` przemianować na `main()`, przenieść na dół i dodać magiczny koniec pliku (3. rozdział).
7. Wybrać coś do przetestowania, np. odsłanianie pól, i przetestować w pliku `main_test.py` — wzór w 3. rozdziale.
8. Reszta ustaleń — zgodnie z konsultacjami.

**Comment by MarcinCiura** [comment]
Aaa. Teraz przeczytałem Pana maila o xyzzy — to dobry pomysł, żeby Pański program był ciut bardziej zaawansowany. Nie mam więcej próśb co do funkcjonalności. Co do formatowania itp. — będę zamieszczał zestawy uwag do skutku, czyli aż kod mi się będzie podobał.

**Comment by Misfit382** [comment]
Dodane.

**Comment by MarcinCiura** [comment]
Dobrze, że dodane, ale co z uwagami?

**Comment by Misfit382** [comment]
A przerpaszam, nie zauważyłem. Już poprawiam

**Comment by Misfit382** [comment]
Szanowny Panie Doktorze,
Dodałem zmiany - wydaje mi się że o to chodziło

**Comment by Misfit382** [comment]
co do testów, aby nie iterować po obiektach klasy, zrobiłem drugą tablicę (jest to tablica jednowymiarowa, w której zawarta "plansza" w miejsce 0 czyli 1 miejsce w górnym lewym roku została dodana mina, i funkcja testowa test_fill_func poprawnie sprawdza że tam jest mina.

**Comment by Misfit382** [comment]
Oczywiście, moge to zrobić w taki sposób aby iterować po klasie Cell, ale nie wiem czy jest sens

**Comment by Misfit382** [comment]
Szanowny Panie Doktorze,
Dodałem o ostatnią rzecz o którą Pan prosił.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan dziewiętnasty. W wolnej chwili:
1. [Poprawić docstring](https://github.com/Misfit382/JS-minesweeper/blob/49ca904c60270c2facd082de34becdc2d3daedad/main_test.py#L1).
2. Kolory lepiej nazywać wg zastosowania, nie wg zawartości (2. rozdział).
